### PR TITLE
Add method to unmock

### PR DESCRIPTION
**Pull request by ertrzyiks**
What do you think about possibility to unmock superagent request? I like to write mocked http response just before asserters to make it clean, but this approach require cleanup method.

### CODE REVIEW

**Comment by fdubost** [comment]
Good for me :+1: ! Thanks for contributing :wink:

**Comment by oziks** [comment]
Hi, I would have called it `unset`. Thanks for contributing :smile:

**Comment by ertrzyiks** [comment]
@oziks so you would like to keep object as return value from mock call and just rename `reset` to `unset`? I suppose its doable :)

**Comment by oziks** [comment]
:+1:

**Pull request merged**
